Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Not Found: /users/search
Not Found: /users/search
Not Found: /users/search
Not Found: /users/search
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Internal Server Error: /users/search
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/usr/local/lib64/python3.6/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/usr/local/lib64/python3.6/site-packages/django/middleware/common.py", line 95, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.12/users/search/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /users/search
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/usr/local/lib64/python3.6/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/usr/local/lib64/python3.6/site-packages/django/middleware/common.py", line 95, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.12/users/search/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /users/search
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/usr/local/lib64/python3.6/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/usr/local/lib64/python3.6/site-packages/django/middleware/common.py", line 95, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.12/users/search/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /users/search
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/usr/local/lib64/python3.6/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/usr/local/lib64/python3.6/site-packages/django/middleware/common.py", line 95, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.12/users/search/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /users/search/
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/DonationPlatform-Back/donation_platform/users/views.py", line 41, in post
    queryset = User.objects.filter(
NameError: name 'User' is not defined
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Internal Server Error: /users/search/
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/DonationPlatform-Back/donation_platform/users/views.py", line 42, in post
    Q(username__icontains=username) | Q(email__icontains=email)
NameError: name 'Q' is not defined
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Internal Server Error: /users/search/
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/DonationPlatform-Back/donation_platform/users/views.py", line 44, in post
    Q(username__icontains=username) | Q(email__icontains=email)
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 1438, in _add_q
    split_subq=split_subq, check_filterable=check_filterable,
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 1295, in build_filter
    check_filterable=check_filterable,
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 1438, in _add_q
    split_subq=split_subq, check_filterable=check_filterable,
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 1309, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 1135, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 1563, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: erased_at, erased_reason, id, organization, organization_id, user_email, user_name, user_password, user_state
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Internal Server Error: /users/search/
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/DonationPlatform-Back/donation_platform/users/views.py", line 44, in post
    Q(user_name__icontains=username) | Q(user_email__icontains=email)
NameError: name 'username' is not defined
Internal Server Error: /users/search/
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/DonationPlatform-Back/donation_platform/users/views.py", line 44, in post
    Q(user_name__icontains=username) | Q(user_email__icontains=email)
NameError: name 'username' is not defined
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Internal Server Error: /users/search/
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/DonationPlatform-Back/donation_platform/users/views.py", line 43, in post
    logger = logging.getLogger(__name__)
NameError: name 'logging' is not defined
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Valor de username: admin_2
Valor de email: 
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Valor de username: admin_2
Valor de email: 
Valor de username: admin
Valor de email: 
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Internal Server Error: /users/create/
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/root/DonationPlatform-Back/donation_platform/users/views.py", line 37, in perform_create
    return super().create(request, *args, **kwargs)
NameError: name 'request' is not defined
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Internal Server Error: /users/create/
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/root/DonationPlatform-Back/donation_platform/users/views.py", line 33, in perform_create
    request.data['user_password'] = hashed_password
NameError: name 'request' is not defined
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
Watching for file changes with StatReloader
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
Watching for file changes with StatReloader
Not Found: /
Not Found: /favicon.ico
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
Watching for file changes with StatReloader
C:\Users\Cami\Desktop\Queenscoders\DonationPlatform-Back\donation_platform\donation_platform\urls.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
Watching for file changes with StatReloader
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
Watching for file changes with StatReloader
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
Watching for file changes with StatReloader
C:\Users\Cami\Desktop\Queenscoders\DonationPlatform-Back\donation_platform\donation_platform\settings.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
Watching for file changes with StatReloader
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
Watching for file changes with StatReloader
C:\Users\Cami\Desktop\Queenscoders\DonationPlatform-Back\donation_platform\donation_platform\models.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'python' implementation: libpq library not found
Watching for file changes with StatReloader
